global:
  scrape_interval: 10s
  evaluation_interval: 30s   # how often rules are evaluated

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "todo-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:9201"]

